(function(E,n){var B,C;function F(){h.width=n.innerWidth;h.height=n.innerHeight;p=canvas.width;v=canvas.height;l.mouse_trace=0}function G(){h.width=p;var a=p/2,b=v/2;B=0.2*(c.x-p/2);C=0.2*(c.y-p/2);l.mouse_trace>N&&(r||setTimeout(function(){l.mouse_trace=0;r=!1;z="rgb(0,0,0)";k=200},1E4),r=!0);r&&(z="rgb(0,"+D+",0)",a+=Math.sin(s)*k,b+=Math.cos(s)*k,D=Math.round(-0.01*k*k+2*k),k-=0.34);a+=B;b+=C;O();var d=new H,f=a+40*c.cx,w=b+40*c.cy;r&&(f+=Math.sin(s)*k,w+=Math.cos(s)*k);d.addEye({size:12,x:f-15,
y:w});d.addEye({size:9,x:f+15,y:w});d.addBody({size:140,x:a,y:b,color:z});d.render(e);P(a,b);e.drawImage(I,-(1920-p)/2,v-250);!A||t||r||Q(d.getEyes());s+=0.1;q&&(z=q);!t&&u.rays?(q=e.createRadialGradient(a,b,70,f,w,20),q.addColorStop(0,"#000"),q.addColorStop(1,"rgb("+Math.round(x)+",0,0)"),x=Math.min(200,x+1.5)):(x=0,q="rgb(0,0,0)");requestAnimationFrame(G)}function Q(a){var b=a.length;m.setChunkSize(30);e.beginPath();for(e.lineCap="round";b--;){var d=a[b];e.strokeStyle="rgba(252,100,0,.8)";e.lineWidth=
1.4*d.size;m.drawQuadraticCurve(c.x,c.y,c.x,c.y,d.x,d.y);e.stroke();e.strokeStyle="#FF0000";e.lineWidth=0.6*d.size;m.drawQuadraticCurve(c.x,c.y,c.x,c.y,d.x,d.y)}e.stroke();e.closePath();R();S();m.setChunkSize(10);e.beginPath();e.fillStyle="rgba(252,100,0,.8)";m.drawStar(c.x,c.y,20,40,20);e.fill();e.closePath();h.style.cursor="none";u.stop_shooting||(u.stop_shooting=setTimeout(function(){A=!1;t=!0;for(var a=10;a--;){var b=new y(c.x,c.y);b.size=6*Math.random();b.gravity=0.2;g.exploding.push(b)}for(a=
g.exploding.length;350<a;)g.exploding.shift(),a--;u.stop_shooting=null},3E3))}function J(a,b){for(var d in a)"undefined"!=typeof b[d]&&(a[d]=b[d]);return a}function O(){for(var a in g)for(var b=g[a].length;b--;)g[a][b].render(e),g[a][b].update()}function R(){var a=new y(c.x,c.y);a.alpha=0.8;a.velX=1*Math.random()-0.5;a.velY=-5*Math.random();a.size=15*Math.random();a.gravity=-0.05;a.color="50,50,50";g.smoke.push(a);for(a=g.smoke.length;1E3<a;)g.smoke.shift(),a--}function P(a,b){for(var d=0;12.5>d;d+=
0.5){var f=new y(a+70*Math.cos(d),b+70*Math.sin(d));f.size=12*Math.random();f.gravity=0;f.alpha=0.8;f.velX=1*Math.random()-0.5;f.velY=1*Math.random()-0.5;f.color="0,"+D+",0";g.hair.push(f)}for(d=g.hair.length;200<d;)g.hair.shift(),d--}function S(){var a=5*Math.random(),b=5*Math.random();h.style.top=b+"px";h.style.left=a+"px";setTimeout(function(){h.style.top=-b+"px";h.style.left=-a+"px";setTimeout(function(){h.style.top=0;h.style.left=0},30)},30)}function y(a,b){this.size=2;this.color="0,0,0";this.x=
a;this.y=b;this.velX=20*Math.random()-10;this.velY=20*Math.random()-10;this.gravity=0.2;this.alpha=1;this.type="perfect"}var h=E.getElementById("canvas"),p=800,v=800,m=new IrregularShapes,T=1E3/60,l={},u={},g={smoke:[],exploding:[],hair:[]},K=100+1E3*Math.random(),N=100,D=0,k=200,I=new Image;I.src="bg.png";var e=h.getContext("2d");C=B=0;var c={x:0,y:0,cx:0,cy:0},L=0,M=0,A=!1,t=!1,r=!1,z="rgb(0,0,0)",s=0,x=0,q=null;F();m.setContext(e);E.addEventListener("mousemove",
function(a){t||(50<Math.max(Math.abs(c.x-L),Math.abs(c.y-M))&&200>=Math.sqrt(Math.pow(c.x-p/2,2)+Math.pow(c.y-v/2,2))&&l.mouse_trace++,L=c.x,M=c.y,c.x=a.pageX,c.y=a.pageY,c.cx=1/(p/2)*c.x-1,c.cy=1/(v/2)*c.y-1,clearTimeout(u.rays),A||(x=0,q=!1),u.rays=setTimeout(function(){t||(A=!0,setTimeout(function(){t=!1;h.style.cursor="default"},1E4))},3E3))},!1);n.addEventListener("resize",F,!1);n.requestAnimationFrame=function(){return n.requestAnimationFrame||n.webkitRequestAnimationFrame||n.mozRequestAnimationFrame||
function(a){n.setTimeout(a,T)}}();e.ellipse=function(a,b,d,f){a-=d/2;b-=f/2;var c=0.5522848*(d/2),e=0.5522848*(f/2),g=a+d,h=b+f;d=a+d/2;f=b+f/2;this.beginPath();this.moveTo(a,f);this.bezierCurveTo(a,f-e,d-c,b,d,b);this.bezierCurveTo(d+c,b,g,f-e,g,f);this.bezierCurveTo(g,f+e,d+c,h,d,h);this.bezierCurveTo(d-c,h,a,f+e,a,f);this.closePath();this.fill()};var H=function(){this.specs={};this.specs.eyes=[]};H.prototype={addBody:function(a){a=a||{};this.specs.body={size:140,x:400,y:400,color:"#000",type:"perfect"};
J(this.specs.body,a)},addEye:function(a){this.specs.eyes.push({color:"#FFF",size:80,x:400,y:400,type:"perfect"});J(this.specs.eyes[this.specs.eyes.length-1],a)},getEyes:function(){return this.specs.eyes},render:function(a){if(this.specs.body){var b=this.specs.body;a.beginPath();a.fillStyle=b.color;"perfect"==b.type?a.arc(b.x,b.y,b.size/2,0,2*Math.PI):m.drawArc(b.x,b.y,b.size/2,0,2*Math.PI);a.fill();a.closePath()}if(0<this.specs.eyes.length){l.blinking||(l.blinking=0);for(var b=this.specs.eyes,d=b.length,
c=0;c<d;c++){var e=b[c];a.beginPath();a.fillStyle=e.color;l.blinking<K?"perfect"==e.type?a.ellipse(e.x,e.y,1.4*e.size,2*e.size):m.drawArc(e.x,e.y,e.size,0,2*Math.PI):(a.ellipse(e.x,e.y,1.4*e.size,4),c==d-1&&(l.blinking=0,K=100+1E3*Math.random()));a.fill();a.closePath()}l.blinking++}}};y.prototype.update=function(){this.x+=this.velX;this.y+=this.velY;this.velY+=this.gravity;this.alpha-=0.01};y.prototype.render=function(a){a.beginPath();a.fillStyle="rgba("+this.color+", "+this.alpha+")";"imperfect"==
this.type?m.drawArc(this.x,this.y,this.size,0,2*Math.PI):a.arc(this.x,this.y,this.size,0,2*Math.PI,!1);a.fill();a.closePath()};G()})(document,window);
